config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  devise_for :users
  resources :castles do
    resources :rentals, only: %i[new create]
  end
  resources :rentals, only: %i[index destroy]
  get "search", to: 'pages#search'
  get "earnings", to: 'castles#earnings'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/castle.rb
class Castle < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  belongs_to :user
  has_many :rentals, dependent: :destroy
  has_one_attached :photo

  validates :name, :address, presence: true, uniqueness: true
  validates :daily_rate, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 999999 }
  validates :photo, presence: true

  def self.rental_search(query)
    where("name LIKE :query OR address LIKE :query", query: "%#{query}%")
  end
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :castle

  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :check_dates
  validate :check_rented

  private

  def check_dates
    if start_date.nil? && end_date.nil?
      errors.add(:start_date, "")
    elsif start_date.present? && start_date < Date.today
      errors.add(:start_date, "can't be in the past")
    elsif end_date.present? && end_date < Date.today
      errors.add(:end_date, "can't be in the past")
    elsif end_date < start_date
      errors.add(:end_date, "can't be before the start date")
    end
  end

  def check_rented
    rentals = Rental.where(castle: self.castle)
    rentals.each do |rental|
      if (rental.start_date..rental.end_date).include?(start_date..end_date)
        errors.add(:end_date, "The selected date is not available")
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :rentals
  has_many :castles
  has_one_attached :photo

  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :photo])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :photo])
  end
end

app/controllers/castles_controller.rb
class CastlesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :require_authorization_owner, only: [:edit, :update, :destroy]
  before_action :find_castle, only: [:show, :edit, :update, :destroy, :require_authorization_owner]

  def index
    @castles = Castle.all
  end

  def show
    @castle = Castle.find(params[:id])
    @rental = Rental.new
    @markers = [{
      lat: @castle.latitude,
      lng: @castle.longitude
    }]
  end

  def earnings
    @castles = current_user.castles
    @earnings_table = []
    @castles.each do |castle|
      castle.rentals.each do |rental|
        days = (rental.end_date - rental.start_date).to_i + 1
        rental.total_rental = rental.castle.daily_rate * days.to_f
        @earnings_table << {
          castle: castle,
          rental: rental,
          total_days: days,
          total_rental: rental.total_rental,
          daily_rate: castle.daily_rate,
          start_date: rental.start_date,
          end_date: rental.end_date
        }
      end
    end
    @total_earnings = @earnings_table.sum { |entry| entry[:total_rental] }
  end

  def new
    @castle = Castle.new
    @user = current_user
  end

  def create
    @castle = Castle.new(castle_params)
    @user = current_user
    @castle.user = @user

    respond_to do |format|
      if @castle.save
        format.html { redirect_to castle_path(@castle), notice: "Castle was successfully created." }
        @castle.save
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @castle.user = @user
    if @castle.update(castle_params)
      redirect_to @castle, notice: "Castle was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @castle.destroy
    redirect_to castles_path, notice: 'Castle was successfully deleted.', status: :see_other
  end

  private

  def castle_params
    params.require(:castle).permit(:name, :description, :address, :daily_rate, :photo, :latitude, :longitude)
  end

  def find_castle
    @castle = Castle.find(params[:id])
  end

  def require_authorization_owner
    castle = Castle.find(params[:id])
    unless current_user.id == castle.user_id
      redirect_to castles_path, alert: "Access denied. You need to be the owner of the castle."
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
  end

  def search
    @castles = params[:place].present? ? Castle.rental_search(params[:place]) : Castle.all
    return unless params[:checkin].present? || params[:checkout].present?

    if params[:checkin].empty? || params[:checkout].empty?
      redirect_to root_path, notice: "Please fill in both date fields."
    else
      check_checkin_checkout
      rentals = Rental.where("(start_date, end_date) OVERLAPS (?, ?)", params[:checkin], params[:checkout])
      castles_rented_ids = rentals.map(&:castle_id)
      @castles = @castles.where.not(id: castles_rented_ids)
    end
  end

  def check_checkin_checkout
    if Date.parse(params[:checkin]) < Date.today || Date.parse(params[:checkout]) < Date.today
      redirect_to root_path, notice: "Check-in or check-out can't be in the past."
    elsif params[:checkout] < params[:checkin]
      redirect_to root_path, notice: "Check-out must be greater than check-in."
    end
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_castle, only: [:new, :create]
  before_action :set_user, only: [:index, :create]

  def new
    @rental = @castle.rentals.build
  end

  def create
    @rental = @castle.rentals.build(rental_params)
    @rental.user = @user
    if @rental.save
      redirect_to rentals_path, notice: "Rental was successfully created."
    else
      render "castles/show", status: :unprocessable_entity
    end
  end

  def index
    @rentals = Rental.where(user_id: @user.id)
  end

  def destroy
    @rental = Rental.find(params[:id])
    @rental.destroy
    redirect_to rentals_path, notice: "Rental was successfully destroyed.", status: :see_other
  end

  private

  def set_castle
    @castle = Castle.find(params[:castle_id])
  end

  def set_user
    @user = current_user
  end

  def rental_params
    params.require(:rental).permit(:start_date, :end_date)
  end
end

app/controllers/users/devise_controller.rb
class Users::DeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/castles/_form.html.erb
<div class="container my-5">
  <%= simple_form_for castle do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :daily_rate %>
    <%= f.input :photo, as: :file %>
    <%= f.submit :submit, class: "btn btn-primary" %>

  <% end %>
</div>

app/views/castles/earnings.html.erb
<div class="container my-5">
<div class="d-flex justify-content-between">
  <h1 class= 'fs-3'>My castles and reservations</h1>
  <h5 class="new-castle"><%= link_to 'new castle', new_castle_path(@castle) %></h5>
</div>
  <hr>
  <div class="row justify-content-start" style="gap: 1.2rem" >
    <h5>Available for rent:</h5>
    <% @castles.each do |castle| %>
      <div class="col-lg-3 col-md-4 mb-3">
        <div class="card" >
          <%= cl_image_tag castle.photo.key, height: 200, width: 300, crop: :fill %>
          <div class="card-body">
            <h5 class="card-title"><%= link_to castle.name, castle_path(castle) %></h5>
            <p class="card-text"><%= castle.address %></p>
            <div class='d-flex justify-content-between'>
              <p><%= number_to_currency(castle.daily_rate) %>/night</p>
            </div>
            <div>
              <%= link_to castle_path(castle), class:'text-primary', style:"text-decoration: none" do %>
                <i class="fa-solid fa-circle-info"></i>
              <% end %>
              <% if current_user.id == castle.user_id %>
                <%= link_to edit_castle_path(castle), class:'text-warning', style:"text-decoration: none" do %>
                  <i class="fa-solid fa-pen"></i>
                <% end %>
                <%= link_to castle_path(castle), data:{ turbo_method: :delete, turbo_confirm: "Are you sure?" }, class:'text-danger' do %>
                  <i class="fa-solid fa-trash-can"></i>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <hr>
<h5>My earnings:</h5>
<div class="table-responsive">
  <table class="table table-bordered table-sm">
    <thead>
      <tr>
        <th style="width: 25%">Castle</th>
        <th style="width: 12%">Client Email</th>
        <th style="width: 8%">Start Date</th>
        <th style="width: 8%">End Date</th>
        <th style="width: 7%">Total Days</th>
        <th style="width: 10%">Daily Rate</th>
        <th style="width: 10%">Total Amount</th>
      </tr>
    </thead>
    <tbody>
      <% @earnings_table.each do |entry| %>
        <tr>
          <td><%= entry[:castle].name %></td>
          <td><%= entry[:rental].user.email %></td>
          <td><%= entry[:start_date].strftime('%d/%m/%Y') %></td>
          <td><%= entry[:end_date].strftime('%d/%m/%Y') %></td>
          <td><%= entry[:total_days] %></td>
          <td><%= number_to_currency(entry[:daily_rate]) %></td>
          <td><%= number_to_currency(entry[:total_rental]) %></td>
        </tr>
      <% end %>
      <tr>
        <td colspan="6" class="text-end"><strong>Total Earnings:</strong></td>
        <td colspan="1"><%= number_to_currency(@total_earnings) %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/castles/edit.html.erb
<div class="container my-5">
  <h1>Edit Castle</h1>

  <%= render 'form', castle: @castle %>
  <%= link_to castles_path, style:"text-decoration: none" do %>
    <i class="fa-solid fa-reply-all"></i>
  <% end %>
  <%= link_to castle_path(@castle), class:'text-primary', style:"text-decoration: none" do %>
    <i class="fa-solid fa-circle-info"></i>
  <% end %>
</div>

app/views/castles/index.html.erb
<div class="container my-5">
<div class="d-flex justify-content-between">
  <h1 class="fs-3">Our Castles</h1>
  <h5 class="m-0 p-0 d-flex align-items-center"><%= link_to "new castle", new_castle_path(@castle), class: "btn btn-primary" %></h5>
</div>
  <hr>
  <div class="row justify-content-center" style="gap: 1.2rem" >
    <% @castles.each do |castle| %>
      <div class="col-lg-3 col-md-4">
        <div class="card" >
          <%= cl_image_tag castle.photo.key, height: 200, width: 300, crop: :fill %>
          <div class="card-body">
            <h5 class="card-title"><%= link_to castle.name, castle_path(castle) %></h5>
            <p class="card-text"><%= castle.address %></p>
            <div class='d-flex justify-content-between'>
              <p><%= number_to_currency(castle.daily_rate) %>/night</p>
            </div>
            <div>
              <%= link_to castle_path(castle), class: "text-primary", style: "text-decoration: none" do %>
                <i class="fa-solid fa-circle-info"></i>
              <% end %>
              <% if user_signed_in? && (current_user.id == castle.user_id) %>
                <%= link_to edit_castle_path(castle), class: "text-warning", style: "text-decoration: none" do %>
                  <i class="fa-solid fa-pen"></i>
                <% end %>
                <%= link_to castle_path(castle), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "text-danger" do %>
                  <i class="fa-solid fa-trash-can"></i>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/castles/new.html.erb
<div class="container my-5">
  <h1>New Castle</h1>

  <%= render 'form', castle: @castle %>
  <%= link_to castles_path, style:"text-decoration: none" do %>
    <i class="fa-solid fa-reply-all"></i>
  <% end %>
</div>

app/views/castles/show.html.erb
<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-9">
      <%# title and image %>
      <div class="d-flex flex-column justify-content-center">
        <h1 class='my-3 mx-4'><%= @castle.name %></h1>
        <%= cl_image_tag @castle.photo.key, height: 450, w_auto: 300, crop: :fill, :radius => 20 %>
      </div>
      <%# description and new_rental %>
      <div class="d-flex align-items-center">
        <div class="m-3">
          <div class="m-3">
            <p class='fs-4 mt-4'><i class="fa-regular fa-map fs-3 me-2"></i> <%= @castle.address %></p>
            <p class='fs-5'><%= @castle.description %></p>
          </div>
          <%# links %>
          <div class="d-flex justify-content-between mx-4 ">
            <div>
              <%= link_to castles_path, style: "text-decoration: none" do %>
                <i class="fa-solid fa-reply-all"></i>
              <% end %>
              <% if current_user.id == @castle.user_id %>
                <%= link_to edit_castle_path(@castle), class: 'text-warning', style: "text-decoration: none" do %>
                  <i class="fa-solid fa-pen"></i>
                <% end %>
                <%= link_to castle_path(@castle), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'text-danger' do %>
                  <i class="fa-solid fa-trash-can"></i>
                <% end %>
              <% end %>
              </div>
              <p class="pe-4"><strong><%= number_to_currency(@castle.daily_rate) %>/night</strong></p>
          </div>

        </div>
        <div class="m-4 w-50">
          <h4>New Rental</h4>
          <%= render 'rentals/form'%>
        </div>
      </div>
      <div class="m-3" style="width: 100%; height: 500px;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Royal Stays</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= favicon_link_tag asset_path("favicon.png") %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/flashes" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="hero"></div>
<div class="layer"></div>
<div class="container-search-bar">
  <h1>Royal Stays</h1>
  <form action="/search" method="get">
    <input type="input" name="place" class="search-place" placeholder="place">
    <input type="date" name="checkin" class="search-checkin">
    <input type="date" name="checkout" class="search-checkout">
    <button type="submit" class="search-btn"><i class="fa-solid fa-magnifying-glass"></i></button>
  </form>
</div>

app/views/pages/search.html.erb
<div class="container my-5">
<div class="d-flex justify-content-between">
  <h1 class= 'fs-3'>Ours Castles (<%= @castles.count %>)</h1>
  <h5 class="new-castle"><%= link_to 'new castle', new_castle_path(@castle) %></h5>
</div>
  <hr>
  <div class="row justify-content-center" style="gap: 1.2rem" >
    <% if @castles.empty? %>
      <h4>There is no castle available for these dates.</h4>
    <% else %>
      <% @castles.each do |castle| %>
        <div class="col-lg-3 col-md-4">
          <div class="card" >
            <%= cl_image_tag castle.photo.key, height: 200, width: 300, crop: :fill %>
            <div class="card-body">
              <h5 class="card-title"><%= link_to castle.name, castle_path(castle) %></h5>
              <p class="card-text"><%= castle.address %></p>
              <div class='d-flex justify-content-between'>
                <p><%= number_to_currency(castle.daily_rate) %></p>
              </div>
              <div>
                <%= link_to castle_path(castle), class:'text-primary', style:"text-decoration: none" do %>
                  <i class="fa-solid fa-circle-info"></i>
                <% end %>
                <% if user_signed_in? && (current_user.id == castle.user_id) %>
                  <%= link_to edit_castle_path(castle), class:'text-warning', style:"text-decoration: none" do %>
                    <i class="fa-solid fa-pen"></i>
                  <% end %>
                  <%= link_to castle_path(castle), data:{ turbo_method: :delete, turbo_confirm: "Are you sure?" }, class:'text-danger' do %>
                    <i class="fa-solid fa-trash-can"></i>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <% end %>
</div>

app/views/rentals/_form.html.erb
<%= simple_form_for([@castle, @rental]) do |form| %>
  <% if @rental.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rental.errors.count, "error") %> prohibited this rental from being saved:</h2>
      <ul>
        <% @rental.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inputs">
    <%= form.input :start_date, as: :date, html5: true %>
    <%= form.input :end_date, as: :date, html5: true %>
  </div>

  <div class="form-actions my-3">
    <%= form.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/rentals/index.html.erb
<div class="container my-5">
  <div class="d-flex justify-content-between">
    <h1 class='fs-3'>Rental List (<%= @rentals.count %>)</h1>
  </div>
  <%= link_to castles_path, style: "text-decoration: none" do %>
    <i class="fa-solid fa-reply-all"></i>
  <% end %>
  <hr>
  <div class="row justify-content-center" style="gap: 1.2rem" >
    <% @rentals.each do |rental|
         days = rental.end_date - rental.start_date
         rental.total_rental = rental.castle.daily_rate * days.to_f %>
      <div class="row g-0 justify-content-center">
        <div class="card-product d-flex flex-direction-column">
          <div class="col-6">
            <%= cl_image_tag rental.castle.photo.key, crop: :fill %>
          </div>
          <div class="col-6">
            <div class="card-product-infos ms-4">
              <h5><%= link_to rental.castle.name, castle_path(rental.castle) %></h5>
              <p>Start date: <%= rental.start_date.strftime("%d/%m/%Y") %></p>
              <p>End date: <%= rental.end_date.strftime("%d/%m/%Y") %></p>
              <div class="d-flex justify-content-between">
                <div class='d-flex justify-content-between me-2'>
                  <p><i class="fa-regular fa-calendar-check"></i> <%= days.to_i %> days</p>
                </div>
                <div class='d-flex justify-content-between'>
                  <p>Total: <%= number_to_currency(rental.total_rental) %></p>
                </div>
              </div>
              <%= link_to rental_path(rental), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "text-danger" do %>
                <i class="fa-solid fa-trash-can"></i>
              <% end %>
            </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div>
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "logo.jpg" %>
    <% end %>
  </div>
  <div class="d-flex">
    <div class="btn-group">
      <button type="button" class=" d-flex btn btn-secondary" data-bs-toggle="dropdown" aria-expanded="false">
        <div class="d-flex align-items-center">
          <i class="fa-solid fa-bars me-2"></i>
          <% if user_signed_in? && !current_user.photo.key.nil? %>
            <%= cl_image_tag current_user.photo.key, height: 35, width: 35, crop: :fill , class: "rounded-5"%>
          <% else %>
            <i class="fa-solid fa-circle-user fs-3"></i>
          <% end %>
        </div>
      </button>
      <ul class="dropdown-menu dropdown-menu-end bg-secondary mt-3">
        <li><%= link_to "All Castles", castles_path , class: "dropdown-item"%></li>
        <% if user_signed_in? %>
          <li><%= link_to "My Reservations", rentals_path, class: "dropdown-item"%></li>
          <% if current_user.castles.any? %>
            <li><%= link_to "My Earnings", earnings_path, class: "dropdown-item" %></li>
          <% end %>
          <li><%= link_to "Edit account", edit_user_registration_path, class: "dropdown-item"%></li>
          <li><hr class="dropdown-divider"></li>
          <li><%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item"%></li>
        <% else %>
          <li><hr class="dropdown-divider"></li>
          <li><%= link_to "Login", new_user_session_path , class: "dropdown-item"%></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>